### ISSUE TITLE
AuthService Injection Error

### ISSUE THREAD

**Issue by taofcode** [duluca/lemon-mart#109]
I am following the book as we go but seem to have got that error and im failing to get the App to display the corrrect page that is login

main.ts:6 ERROR NullInjectorError: R3InjectorError(AppModule)[AuthService -> AuthService]: 
  NullInjectorError: No provider for AuthService!
    at NullInjector.get (core.mjs:8890:27)
    at R3Injector.get (core.mjs:9334:33)
    at R3Injector.get (core.mjs:9334:33)
    at ChainedInjector.get (core.mjs:14018:36)
    at lookupTokenUsingModuleInjector (core.mjs:4608:39)
    at getOrCreateInjectable (core.mjs:4656:12)
    at Module.ɵɵdirectiveInject (core.mjs:11801:19)
    at NodeInjectorFactory.LoginComponent_Factory [as factory] (login.component.ts:25:28)
    at getNodeInjectable (core.mjs:4862:44)
    at instantiateAllDirectives (core.mjs:12629:27)

**Comment by duluca** [comment]
There are a couple of things to check.

In your service implementation, set the `providedIn: 'root'` property:
```
@Injectable({
  providedIn: 'root',
})
export class InMemoryAuthService extends AuthService
```

In `app.config.ts` make sure the service is provided with the factory:
```
export const appConfig: ApplicationConfig = {
   providers: [
     //...
    {
      provide: AuthService,
      useFactory: authFactory,
    },
    //...
   ],
}
```

**Comment by duluca** [comment]
@taofcode sorry for the delayed response were you able to figure it out?
